name: saber
description: A cross-platform libre notes app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.8.1+8010

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  dynamic_color: ^1.5.4

  flutter_staggered_grid_view: ^0.6.2

  go_router: ^6.0.1
  path_to_regexp: ^0.4.0

  # todo: use pub.dev when the new release (> 1.0.4) is available
  perfect_freehand:
    git:
      url: https://github.com/steveruizok/perfect-freehand-dart

  path_provider: ^2.0.11

  shared_preferences: ^2.0.17
  flutter_secure_storage: ^7.0.1

  # Don't use encrypted_shared_preferences because it's insecure:
  # https://github.com/roulljdh/encrypted_shared_preferences/issues/10.
  # This remains to migrate existing users to flutter_secure_storage, and also
  # because flutter_secure_storage doesn't support macOS without a paid Apple Developer account:
  # https://github.com/adil192/saber/issues/257
  encrypted_shared_preferences: ^3.0.1

  url_launcher: ^6.1.8

  package_info_plus: ^3.0.2

  nextcloud:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/nextcloud

  collapsible: ^1.0.0

  vector_math: ^2.1.2

  intl: ^0.17.0

  crypto: ^3.0.2
  encrypt: ^5.0.1

  http: ^0.13.5

  keybinder: ^1.0.1

  pdf: ^3.8.4
  share_plus: ^6.3.0
  file_picker: ^5.2.5

  regexed_validator: ^2.0.0+1

  slang: ^3.9.0
  slang_flutter:

  flutter_colorpicker: ^1.0.3

  google_fonts: ^4.0.1

  font_awesome_flutter: ^10.3.0

  flutter_svg: ^2.0.0+1

  # when updated, check if image_picker supports more platforms for Editor.pickPhoto()
  image_picker: ^0.8.6+1

  defer_pointer: ^0.0.2

  image: ^3.3.0

  image_save: ^5.0.0

  animations: ^2.0.7

  flutter_quill: ^6.2.2
  tuple: ^2.0.1

  window_manager: ^0.3.0

  worker_manager: ^5.0.0

  # https://pub.dev/packages/flutter_sharing_intent will have better cross-platform support
  # but it's not yet ready (January 2023)
  # Using a fork because the original uses an old version of kotlin and doesn't support text files
  receive_sharing_intent:
    git:
      url: https://github.com/adil192/receive_sharing_intent.git
      ref: receive-.txt-v2
  open_as_default:
    git:
      url: https://github.com/adil192/open_as_default.git

  js: ^0.6.4

  onyxsdk_pen:
    path: packages/onyxsdk_pen_dummy

  flex_seed_scheme: ^1.1.0

  device_info_plus: ^8.0.0

  screenshot: ^1.3.0

  collection: ^1.17.0

  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  # todo: use pub.dev when https://github.com/mrrhak/icons_launcher/pull/28
  # is merged and a new release is available (> 2.0.7)
  icons_launcher:
    git:
      url: https://github.com/adil192/icons_launcher.git
      ref: Add-M3-Material-Icons

  process_run: ^0.12.5+2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


# flutter pub run icons_launcher:create
icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffc800"
      adaptive_foreground_image: "assets/icon/icon_maskable.png"
      adaptive_monochrome_image: "assets/icon/icon_monochrome.png"
    ios:
      enable: true
      image_path: "assets/icon/icon_opaque.png"
    linux:
      enable: true
    web:
      enable: true
    windows:
      enable: true
    macos:
      enable: true
      image_path: "assets/icon/icon_opaque.png"

flutter_native_splash:
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # See https://pub.dev/packages/flutter_native_splash for more information.

  # Use color to set the background of your splash screen to a solid color.
  color: "#ffffff"
  color_dark: "#000000"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/icon/resized/icon-512x512.png

  # disable generating a splash screen on a given platform.
  android: false
  ios: false
  #web: false
