name: Run onyxsdk_pen tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/onyxsdk_pen/**'
  push:
    paths:
      - 'packages/onyxsdk_pen/**'

jobs:
  run-onyx-tests:
    name: Run Flutter tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libsecret-1-dev libjsoncpp-dev ghostscript
          version: 1.0
          execute_install_scripts: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      - name: Run tests
        working-directory: packages/onyxsdk_pen
        run: flutter test

      - name: Lints
        uses: invertase/github-action-dart-analyzer@v3
        with:
          working-directory: packages/onyxsdk_pen