name: Run onyxsdk_pen tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/onyxsdk_pen/**"
      - .github/workflows/onyxsdk_pen_tests.yml
  push:
    paths:
      - "packages/onyxsdk_pen/**"
      - .github/workflows/onyxsdk_pen_tests.yml

jobs:
  run-onyx-tests:
    name: Run Flutter tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: "./.github/shared_workflows/install_apt_dependencies"

      - name: Setup Flutter
        uses: adil192/setup-flutter-submodule@v1
        with:
          flutter-path: submodules/flutter

      - name: Run tests
        working-directory: packages/onyxsdk_pen
        run: flutter test

      - name: Lints
        uses: invertase/github-action-dart-analyzer@v3
        with:
          working-directory: packages/onyxsdk_pen
